### ISSUE TITLE
請問能使用CSS來調整非日文行的字型與顏色

### ISSUE THREAD

**Issue by po-hsiang** [FlandreDaisuki/JP-Lyric-with-Ruby#3]
需求：能使用CSS來調整非日文行的字型與顏色

範例：
![image](https://user-images.githubusercontent.com/12793946/56183043-4484a900-6047-11e9-81de-6bfbda767fda.png)

感謝

**Comment by po-hsiang** [comment]
> 例如能用CSS調整中文翻譯的設定

**Comment by po-hsiang** [comment]
不小心 Close 到 issue, 重開

**Comment by yanagiragi** [comment]
I can do a PR with that 💃

**Comment by FlandreDaisuki** [comment]
多個原文的 class 跟其他的 class 就好了吧
至於空行 CSS 有 `:empty` 可以處理

原文的 `.lyric-row.japanese`
其他有字的 `.lyric-row` (不用特別處理)
其他空行 `.lyric-row:empty` (不用特別處理)

@yanagiragi 那就給你ㄅ

**Comment by FlandreDaisuki** [comment]
範例：

```css
.lyric-row {
  font-size: 1.6rem;
  color: gray;
}
.lyric-row.japanese {
  font-size: 1.4rem;
  color: black;
}
```
